apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-app-multi-components-repo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/qeyekabd-tenant/test-app-170168188/nodejs-app-multi-components-repo@sha256:7935a00a539e2c5fa260c56c00d9e82a31943e188267b85cbb66b94a5a9cfe6c
        name: my-nodejs
        resources: {}
status: {}
